/*
 * This file was automatically generated by EvoSuite
 * Mon May 21 14:08:31 GMT 2018
 */

package microwave;

import org.junit.Test;
import static org.junit.Assert.*;
import microwave.Preset;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Preset_ESTest extends Preset_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Preset preset0 = new Preset("", 11, 11);
      int int0 = preset0.getTimeToCook();
      assertEquals(11, int0);
      assertEquals(11, preset0.getPowerLevel());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Preset preset0 = new Preset("}1|7P3\".dD)>s9b ", (-2595), (-2595));
      int int0 = preset0.getTimeToCook();
      assertEquals((-2595), int0);
      assertEquals(-2595, preset0.getPowerLevel());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Preset preset0 = new Preset("'|~h}/T90)[FxAF]V", 0, 0);
      int int0 = preset0.getPowerLevel();
      assertEquals(0, int0);
      assertEquals(0, preset0.getTimeToCook());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Preset preset0 = new Preset("", 11, 11);
      int int0 = preset0.getPowerLevel();
      assertEquals(11, int0);
      assertEquals(11, preset0.getTimeToCook());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Preset preset0 = new Preset((String) null, (-1), 0);
      preset0.getName();
      assertEquals(-1, preset0.getTimeToCook());
      assertEquals(0, preset0.getPowerLevel());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Preset preset0 = new Preset("", 11, 11);
      preset0.getName();
      assertEquals(11, preset0.getPowerLevel());
      assertEquals(11, preset0.getTimeToCook());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Preset preset0 = new Preset("'|~h}/T90)[FxAF]V", 0, 0);
      int int0 = preset0.getTimeToCook();
      assertEquals(0, int0);
      assertEquals(0, preset0.getPowerLevel());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Preset preset0 = new Preset("", 11, 11);
      preset0.setTimeToCook(11);
      assertEquals(11, preset0.getPowerLevel());
      assertEquals(11, preset0.getTimeToCook());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Preset preset0 = new Preset("'|~h}/T90)[FxAF]V", 0, 0);
      preset0.getName();
      assertEquals(0, preset0.getPowerLevel());
      assertEquals(0, preset0.getTimeToCook());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Preset preset0 = new Preset("'|~h}/T90)[FxAF]V", 0, 0);
      preset0.setName("'|~h}/T90)[FxAF]V");
      assertEquals(0, preset0.getTimeToCook());
      assertEquals(0, preset0.getPowerLevel());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Preset preset0 = new Preset("}1|7P3\".dD)>s9b ", (-2595), (-2595));
      preset0.setPowerLevel((-2595));
      assertEquals(-2595, preset0.getPowerLevel());
      assertEquals(-2595, preset0.getTimeToCook());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Preset preset0 = new Preset("", 11, 11);
      String string0 = preset0.toString();
      assertEquals("Preset [name=, timeToCook=11, powerLevel=11]", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Preset preset0 = new Preset("W->@ctyR39}.", (-1628), (-1628));
      int int0 = preset0.getPowerLevel();
      assertEquals((-1628), int0);
      assertEquals(-1628, preset0.getTimeToCook());
  }
}
